// Code generated by go-swagger; DO NOT EDIT.

package t_n_custom_field

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/killbill/kbcli/v3/kbcommon"
)

// DeleteTNCustomFieldReader is a Reader for the DeleteTNCustomField structure.
type DeleteTNCustomFieldReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteTNCustomFieldReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteTNCustomFieldOK()
		result.HttpResponse = response
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		errorResult := kbcommon.NewKillbillError(response.Code())
		if err := consumer.Consume(response.Body(), &errorResult); err != nil && err != io.EOF {
			return nil, err
		}
		return nil, errorResult
	}
}

// NewDeleteTNCustomFieldOK creates a DeleteTNCustomFieldOK with default headers values
func NewDeleteTNCustomFieldOK() *DeleteTNCustomFieldOK {
	return &DeleteTNCustomFieldOK{}
}

/* DeleteTNCustomFieldOK describes a response with status code 200, with default header values.

successful operation
*/
type DeleteTNCustomFieldOK struct {
	HttpResponse runtime.ClientResponse
}

// Code gets the status code for the delete t n custom field o k response
func (o *DeleteTNCustomFieldOK) Code() int {
	return 200
}

// IsSuccess returns true when this delete t n custom field o k response has a 2xx status code
func (o *DeleteTNCustomFieldOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete t n custom field o k response has a 3xx status code
func (o *DeleteTNCustomFieldOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete t n custom field o k response has a 4xx status code
func (o *DeleteTNCustomFieldOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete t n custom field o k response has a 5xx status code
func (o *DeleteTNCustomFieldOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete t n custom field o k response a status code equal to that given
func (o *DeleteTNCustomFieldOK) IsCode(code int) bool {
	return code == 200
}

func (o *DeleteTNCustomFieldOK) Error() string {
	return fmt.Sprintf("[DELETE /plugins/textnow-custom-field-plugin/][%d] deleteTNCustomFieldOK ", 200)
}

func (o *DeleteTNCustomFieldOK) String() string {
	return fmt.Sprintf("[DELETE /plugins/textnow-custom-field-plugin/][%d] deleteTNCustomFieldOK ", 200)
}

func (o *DeleteTNCustomFieldOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteTNCustomFieldBadRequest creates a DeleteTNCustomFieldBadRequest with default headers values
func NewDeleteTNCustomFieldBadRequest() *DeleteTNCustomFieldBadRequest {
	return &DeleteTNCustomFieldBadRequest{}
}

/* DeleteTNCustomFieldBadRequest describes a response with status code 400, with default header values.

Invalid data supplied
*/
type DeleteTNCustomFieldBadRequest struct {
	HttpResponse runtime.ClientResponse
}

// Code gets the status code for the delete t n custom field bad request response
func (o *DeleteTNCustomFieldBadRequest) Code() int {
	return 400
}

// IsSuccess returns true when this delete t n custom field bad request response has a 2xx status code
func (o *DeleteTNCustomFieldBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete t n custom field bad request response has a 3xx status code
func (o *DeleteTNCustomFieldBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete t n custom field bad request response has a 4xx status code
func (o *DeleteTNCustomFieldBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete t n custom field bad request response has a 5xx status code
func (o *DeleteTNCustomFieldBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete t n custom field bad request response a status code equal to that given
func (o *DeleteTNCustomFieldBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *DeleteTNCustomFieldBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /plugins/textnow-custom-field-plugin/][%d] deleteTNCustomFieldBadRequest ", 400)
}

func (o *DeleteTNCustomFieldBadRequest) String() string {
	return fmt.Sprintf("[DELETE /plugins/textnow-custom-field-plugin/][%d] deleteTNCustomFieldBadRequest ", 400)
}

func (o *DeleteTNCustomFieldBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteTNCustomFieldInternalServerError creates a DeleteTNCustomFieldInternalServerError with default headers values
func NewDeleteTNCustomFieldInternalServerError() *DeleteTNCustomFieldInternalServerError {
	return &DeleteTNCustomFieldInternalServerError{}
}

/* DeleteTNCustomFieldInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type DeleteTNCustomFieldInternalServerError struct {
	HttpResponse runtime.ClientResponse
}

// Code gets the status code for the delete t n custom field internal server error response
func (o *DeleteTNCustomFieldInternalServerError) Code() int {
	return 500
}

// IsSuccess returns true when this delete t n custom field internal server error response has a 2xx status code
func (o *DeleteTNCustomFieldInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete t n custom field internal server error response has a 3xx status code
func (o *DeleteTNCustomFieldInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete t n custom field internal server error response has a 4xx status code
func (o *DeleteTNCustomFieldInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete t n custom field internal server error response has a 5xx status code
func (o *DeleteTNCustomFieldInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete t n custom field internal server error response a status code equal to that given
func (o *DeleteTNCustomFieldInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *DeleteTNCustomFieldInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /plugins/textnow-custom-field-plugin/][%d] deleteTNCustomFieldInternalServerError ", 500)
}

func (o *DeleteTNCustomFieldInternalServerError) String() string {
	return fmt.Sprintf("[DELETE /plugins/textnow-custom-field-plugin/][%d] deleteTNCustomFieldInternalServerError ", 500)
}

func (o *DeleteTNCustomFieldInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
