// Code generated by go-swagger; DO NOT EDIT.

package t_n_custom_field

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetTNCustomFieldsParams creates a new GetTNCustomFieldsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetTNCustomFieldsParams() *GetTNCustomFieldsParams {
	return &GetTNCustomFieldsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetTNCustomFieldsParamsWithTimeout creates a new GetTNCustomFieldsParams object
// with the ability to set a timeout on a request.
func NewGetTNCustomFieldsParamsWithTimeout(timeout time.Duration) *GetTNCustomFieldsParams {
	return &GetTNCustomFieldsParams{
		timeout: timeout,
	}
}

// NewGetTNCustomFieldsParamsWithContext creates a new GetTNCustomFieldsParams object
// with the ability to set a context for a request.
func NewGetTNCustomFieldsParamsWithContext(ctx context.Context) *GetTNCustomFieldsParams {
	return &GetTNCustomFieldsParams{
		Context: ctx,
	}
}

// NewGetTNCustomFieldsParamsWithHTTPClient creates a new GetTNCustomFieldsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetTNCustomFieldsParamsWithHTTPClient(client *http.Client) *GetTNCustomFieldsParams {
	return &GetTNCustomFieldsParams{
		HTTPClient: client,
	}
}

/* GetTNCustomFieldsParams contains all the parameters to send to the API endpoint
   for the get t n custom fields operation.

   Typically these are written to a http.Request.
*/
type GetTNCustomFieldsParams struct {

	// Category.
	Category *string

	// FieldName.
	FieldName *string

	// KbTenantID.
	KbTenantID *string

	// ObjectID.
	ObjectID *string

	WithProfilingInfo     *string // If set, return KB hprof headers
	WithStackTrace        *bool   // If set, returns full stack trace with error message
	timeout               time.Duration
	Context               context.Context
	HTTPClient            *http.Client
	ProcessLocationHeader bool // For create APIs that return 201, send another request and retrieve the resource.
}

// WithDefaults hydrates default values in the get t n custom fields params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTNCustomFieldsParams) WithDefaults() *GetTNCustomFieldsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get t n custom fields params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTNCustomFieldsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get t n custom fields params
func (o *GetTNCustomFieldsParams) WithTimeout(timeout time.Duration) *GetTNCustomFieldsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get t n custom fields params
func (o *GetTNCustomFieldsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get t n custom fields params
func (o *GetTNCustomFieldsParams) WithContext(ctx context.Context) *GetTNCustomFieldsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get t n custom fields params
func (o *GetTNCustomFieldsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get t n custom fields params
func (o *GetTNCustomFieldsParams) WithHTTPClient(client *http.Client) *GetTNCustomFieldsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get t n custom fields params
func (o *GetTNCustomFieldsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCategory adds the category to the get t n custom fields params
func (o *GetTNCustomFieldsParams) WithCategory(category *string) *GetTNCustomFieldsParams {
	o.SetCategory(category)
	return o
}

// SetCategory adds the category to the get t n custom fields params
func (o *GetTNCustomFieldsParams) SetCategory(category *string) {
	o.Category = category
}

// WithFieldName adds the fieldName to the get t n custom fields params
func (o *GetTNCustomFieldsParams) WithFieldName(fieldName *string) *GetTNCustomFieldsParams {
	o.SetFieldName(fieldName)
	return o
}

// SetFieldName adds the fieldName to the get t n custom fields params
func (o *GetTNCustomFieldsParams) SetFieldName(fieldName *string) {
	o.FieldName = fieldName
}

// WithKbTenantID adds the kbTenantID to the get t n custom fields params
func (o *GetTNCustomFieldsParams) WithKbTenantID(kbTenantID *string) *GetTNCustomFieldsParams {
	o.SetKbTenantID(kbTenantID)
	return o
}

// SetKbTenantID adds the kbTenantId to the get t n custom fields params
func (o *GetTNCustomFieldsParams) SetKbTenantID(kbTenantID *string) {
	o.KbTenantID = kbTenantID
}

// WithObjectID adds the objectID to the get t n custom fields params
func (o *GetTNCustomFieldsParams) WithObjectID(objectID *string) *GetTNCustomFieldsParams {
	o.SetObjectID(objectID)
	return o
}

// SetObjectID adds the objectId to the get t n custom fields params
func (o *GetTNCustomFieldsParams) SetObjectID(objectID *string) {
	o.ObjectID = objectID
}

// WriteToRequest writes these params to a swagger request
func (o *GetTNCustomFieldsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Category != nil {

		// query param category
		var qrCategory string

		if o.Category != nil {
			qrCategory = *o.Category
		}
		qCategory := qrCategory
		if qCategory != "" {

			if err := r.SetQueryParam("category", qCategory); err != nil {
				return err
			}
		}
	}

	if o.FieldName != nil {

		// query param fieldName
		var qrFieldName string

		if o.FieldName != nil {
			qrFieldName = *o.FieldName
		}
		qFieldName := qrFieldName
		if qFieldName != "" {

			if err := r.SetQueryParam("fieldName", qFieldName); err != nil {
				return err
			}
		}
	}

	if o.KbTenantID != nil {

		// query param kbTenantId
		var qrKbTenantID string

		if o.KbTenantID != nil {
			qrKbTenantID = *o.KbTenantID
		}
		qKbTenantID := qrKbTenantID
		if qKbTenantID != "" {

			if err := r.SetQueryParam("kbTenantId", qKbTenantID); err != nil {
				return err
			}
		}
	}

	if o.ObjectID != nil {

		// query param objectId
		var qrObjectID string

		if o.ObjectID != nil {
			qrObjectID = *o.ObjectID
		}
		qObjectID := qrObjectID
		if qObjectID != "" {

			if err := r.SetQueryParam("objectId", qObjectID); err != nil {
				return err
			}
		}
	}

	// header param WithProfilingInfo
	if o.WithProfilingInfo != nil && len(*o.WithProfilingInfo) > 0 {
		if err := r.SetHeaderParam("X-Killbill-Profiling-Req", *o.WithProfilingInfo); err != nil {
			return err
		}
	}

	// header param withStackTrace
	if o.WithStackTrace != nil && *o.WithStackTrace {
		if err := r.SetQueryParam("withStackTrace", "true"); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
