// Code generated by go-swagger; DO NOT EDIT.

package t_n_custom_field

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/killbill/kbcli/v3/kbcommon"

	"github.com/killbill/kbcli/v3/kbmodel"
)

// GetTNCustomFieldsReader is a Reader for the GetTNCustomFields structure.
type GetTNCustomFieldsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTNCustomFieldsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetTNCustomFieldsOK()
		result.HttpResponse = response
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		errorResult := kbcommon.NewKillbillError(response.Code())
		if err := consumer.Consume(response.Body(), &errorResult); err != nil && err != io.EOF {
			return nil, err
		}
		return nil, errorResult
	}
}

// NewGetTNCustomFieldsOK creates a GetTNCustomFieldsOK with default headers values
func NewGetTNCustomFieldsOK() *GetTNCustomFieldsOK {
	return &GetTNCustomFieldsOK{}
}

/* GetTNCustomFieldsOK describes a response with status code 200, with default header values.

successful operation
*/
type GetTNCustomFieldsOK struct {
	Payload      []*kbmodel.TNCustomField
	HttpResponse runtime.ClientResponse
}

// Code gets the status code for the get t n custom fields o k response
func (o *GetTNCustomFieldsOK) Code() int {
	return 200
}

// IsSuccess returns true when this get t n custom fields o k response has a 2xx status code
func (o *GetTNCustomFieldsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get t n custom fields o k response has a 3xx status code
func (o *GetTNCustomFieldsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get t n custom fields o k response has a 4xx status code
func (o *GetTNCustomFieldsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get t n custom fields o k response has a 5xx status code
func (o *GetTNCustomFieldsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get t n custom fields o k response a status code equal to that given
func (o *GetTNCustomFieldsOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetTNCustomFieldsOK) Error() string {
	return fmt.Sprintf("[GET /plugins/textnow-custom-field-plugin/][%d] getTNCustomFieldsOK  %+v", 200, o.Payload)
}

func (o *GetTNCustomFieldsOK) String() string {
	return fmt.Sprintf("[GET /plugins/textnow-custom-field-plugin/][%d] getTNCustomFieldsOK  %+v", 200, o.Payload)
}

func (o *GetTNCustomFieldsOK) GetPayload() []*kbmodel.TNCustomField {
	return o.Payload
}

func (o *GetTNCustomFieldsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTNCustomFieldsBadRequest creates a GetTNCustomFieldsBadRequest with default headers values
func NewGetTNCustomFieldsBadRequest() *GetTNCustomFieldsBadRequest {
	return &GetTNCustomFieldsBadRequest{}
}

/* GetTNCustomFieldsBadRequest describes a response with status code 400, with default header values.

Invalid data supplied
*/
type GetTNCustomFieldsBadRequest struct {
	HttpResponse runtime.ClientResponse
}

// Code gets the status code for the get t n custom fields bad request response
func (o *GetTNCustomFieldsBadRequest) Code() int {
	return 400
}

// IsSuccess returns true when this get t n custom fields bad request response has a 2xx status code
func (o *GetTNCustomFieldsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get t n custom fields bad request response has a 3xx status code
func (o *GetTNCustomFieldsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get t n custom fields bad request response has a 4xx status code
func (o *GetTNCustomFieldsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get t n custom fields bad request response has a 5xx status code
func (o *GetTNCustomFieldsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get t n custom fields bad request response a status code equal to that given
func (o *GetTNCustomFieldsBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *GetTNCustomFieldsBadRequest) Error() string {
	return fmt.Sprintf("[GET /plugins/textnow-custom-field-plugin/][%d] getTNCustomFieldsBadRequest ", 400)
}

func (o *GetTNCustomFieldsBadRequest) String() string {
	return fmt.Sprintf("[GET /plugins/textnow-custom-field-plugin/][%d] getTNCustomFieldsBadRequest ", 400)
}

func (o *GetTNCustomFieldsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetTNCustomFieldsNotFound creates a GetTNCustomFieldsNotFound with default headers values
func NewGetTNCustomFieldsNotFound() *GetTNCustomFieldsNotFound {
	return &GetTNCustomFieldsNotFound{}
}

/* GetTNCustomFieldsNotFound describes a response with status code 404, with default header values.

Custom fields not found
*/
type GetTNCustomFieldsNotFound struct {
	HttpResponse runtime.ClientResponse
}

// Code gets the status code for the get t n custom fields not found response
func (o *GetTNCustomFieldsNotFound) Code() int {
	return 404
}

// IsSuccess returns true when this get t n custom fields not found response has a 2xx status code
func (o *GetTNCustomFieldsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get t n custom fields not found response has a 3xx status code
func (o *GetTNCustomFieldsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get t n custom fields not found response has a 4xx status code
func (o *GetTNCustomFieldsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get t n custom fields not found response has a 5xx status code
func (o *GetTNCustomFieldsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get t n custom fields not found response a status code equal to that given
func (o *GetTNCustomFieldsNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *GetTNCustomFieldsNotFound) Error() string {
	return fmt.Sprintf("[GET /plugins/textnow-custom-field-plugin/][%d] getTNCustomFieldsNotFound ", 404)
}

func (o *GetTNCustomFieldsNotFound) String() string {
	return fmt.Sprintf("[GET /plugins/textnow-custom-field-plugin/][%d] getTNCustomFieldsNotFound ", 404)
}

func (o *GetTNCustomFieldsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetTNCustomFieldsInternalServerError creates a GetTNCustomFieldsInternalServerError with default headers values
func NewGetTNCustomFieldsInternalServerError() *GetTNCustomFieldsInternalServerError {
	return &GetTNCustomFieldsInternalServerError{}
}

/* GetTNCustomFieldsInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetTNCustomFieldsInternalServerError struct {
	HttpResponse runtime.ClientResponse
}

// Code gets the status code for the get t n custom fields internal server error response
func (o *GetTNCustomFieldsInternalServerError) Code() int {
	return 500
}

// IsSuccess returns true when this get t n custom fields internal server error response has a 2xx status code
func (o *GetTNCustomFieldsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get t n custom fields internal server error response has a 3xx status code
func (o *GetTNCustomFieldsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get t n custom fields internal server error response has a 4xx status code
func (o *GetTNCustomFieldsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get t n custom fields internal server error response has a 5xx status code
func (o *GetTNCustomFieldsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get t n custom fields internal server error response a status code equal to that given
func (o *GetTNCustomFieldsInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *GetTNCustomFieldsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /plugins/textnow-custom-field-plugin/][%d] getTNCustomFieldsInternalServerError ", 500)
}

func (o *GetTNCustomFieldsInternalServerError) String() string {
	return fmt.Sprintf("[GET /plugins/textnow-custom-field-plugin/][%d] getTNCustomFieldsInternalServerError ", 500)
}

func (o *GetTNCustomFieldsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
