// Code generated by go-swagger; DO NOT EDIT.

package t_n_custom_field

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/killbill/kbcli/v3/kbmodel"
)

// NewUpdateTNCustomFieldParams creates a new UpdateTNCustomFieldParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateTNCustomFieldParams() *UpdateTNCustomFieldParams {
	return &UpdateTNCustomFieldParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateTNCustomFieldParamsWithTimeout creates a new UpdateTNCustomFieldParams object
// with the ability to set a timeout on a request.
func NewUpdateTNCustomFieldParamsWithTimeout(timeout time.Duration) *UpdateTNCustomFieldParams {
	return &UpdateTNCustomFieldParams{
		timeout: timeout,
	}
}

// NewUpdateTNCustomFieldParamsWithContext creates a new UpdateTNCustomFieldParams object
// with the ability to set a context for a request.
func NewUpdateTNCustomFieldParamsWithContext(ctx context.Context) *UpdateTNCustomFieldParams {
	return &UpdateTNCustomFieldParams{
		Context: ctx,
	}
}

// NewUpdateTNCustomFieldParamsWithHTTPClient creates a new UpdateTNCustomFieldParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateTNCustomFieldParamsWithHTTPClient(client *http.Client) *UpdateTNCustomFieldParams {
	return &UpdateTNCustomFieldParams{
		HTTPClient: client,
	}
}

/* UpdateTNCustomFieldParams contains all the parameters to send to the API endpoint
   for the update t n custom field operation.

   Typically these are written to a http.Request.
*/
type UpdateTNCustomFieldParams struct {

	// Body.
	Body *kbmodel.TNCustomField

	WithProfilingInfo     *string // If set, return KB hprof headers
	WithStackTrace        *bool   // If set, returns full stack trace with error message
	timeout               time.Duration
	Context               context.Context
	HTTPClient            *http.Client
	ProcessLocationHeader bool // For create APIs that return 201, send another request and retrieve the resource.
}

// WithDefaults hydrates default values in the update t n custom field params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateTNCustomFieldParams) WithDefaults() *UpdateTNCustomFieldParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update t n custom field params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateTNCustomFieldParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update t n custom field params
func (o *UpdateTNCustomFieldParams) WithTimeout(timeout time.Duration) *UpdateTNCustomFieldParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update t n custom field params
func (o *UpdateTNCustomFieldParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update t n custom field params
func (o *UpdateTNCustomFieldParams) WithContext(ctx context.Context) *UpdateTNCustomFieldParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update t n custom field params
func (o *UpdateTNCustomFieldParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update t n custom field params
func (o *UpdateTNCustomFieldParams) WithHTTPClient(client *http.Client) *UpdateTNCustomFieldParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update t n custom field params
func (o *UpdateTNCustomFieldParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update t n custom field params
func (o *UpdateTNCustomFieldParams) WithBody(body *kbmodel.TNCustomField) *UpdateTNCustomFieldParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update t n custom field params
func (o *UpdateTNCustomFieldParams) SetBody(body *kbmodel.TNCustomField) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateTNCustomFieldParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// header param WithProfilingInfo
	if o.WithProfilingInfo != nil && len(*o.WithProfilingInfo) > 0 {
		if err := r.SetHeaderParam("X-Killbill-Profiling-Req", *o.WithProfilingInfo); err != nil {
			return err
		}
	}

	// header param withStackTrace
	if o.WithStackTrace != nil && *o.WithStackTrace {
		if err := r.SetQueryParam("withStackTrace", "true"); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
