// Code generated by go-swagger; DO NOT EDIT.

package t_n_custom_field

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/killbill/kbcli/v3/kbcommon"

	"github.com/killbill/kbcli/v3/kbmodel"
)

// UpdateTNCustomFieldReader is a Reader for the UpdateTNCustomField structure.
type UpdateTNCustomFieldReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateTNCustomFieldReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUpdateTNCustomFieldOK()
		result.HttpResponse = response
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		errorResult := kbcommon.NewKillbillError(response.Code())
		if err := consumer.Consume(response.Body(), &errorResult); err != nil && err != io.EOF {
			return nil, err
		}
		return nil, errorResult
	}
}

// NewUpdateTNCustomFieldOK creates a UpdateTNCustomFieldOK with default headers values
func NewUpdateTNCustomFieldOK() *UpdateTNCustomFieldOK {
	return &UpdateTNCustomFieldOK{}
}

/* UpdateTNCustomFieldOK describes a response with status code 200, with default header values.

successful operation
*/
type UpdateTNCustomFieldOK struct {
	Payload      *kbmodel.TNCustomField
	HttpResponse runtime.ClientResponse
}

// Code gets the status code for the update t n custom field o k response
func (o *UpdateTNCustomFieldOK) Code() int {
	return 200
}

// IsSuccess returns true when this update t n custom field o k response has a 2xx status code
func (o *UpdateTNCustomFieldOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update t n custom field o k response has a 3xx status code
func (o *UpdateTNCustomFieldOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update t n custom field o k response has a 4xx status code
func (o *UpdateTNCustomFieldOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this update t n custom field o k response has a 5xx status code
func (o *UpdateTNCustomFieldOK) IsServerError() bool {
	return false
}

// IsCode returns true when this update t n custom field o k response a status code equal to that given
func (o *UpdateTNCustomFieldOK) IsCode(code int) bool {
	return code == 200
}

func (o *UpdateTNCustomFieldOK) Error() string {
	return fmt.Sprintf("[PUT /plugins/textnow-custom-field-plugin/][%d] updateTNCustomFieldOK  %+v", 200, o.Payload)
}

func (o *UpdateTNCustomFieldOK) String() string {
	return fmt.Sprintf("[PUT /plugins/textnow-custom-field-plugin/][%d] updateTNCustomFieldOK  %+v", 200, o.Payload)
}

func (o *UpdateTNCustomFieldOK) GetPayload() *kbmodel.TNCustomField {
	return o.Payload
}

func (o *UpdateTNCustomFieldOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(kbmodel.TNCustomField)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateTNCustomFieldBadRequest creates a UpdateTNCustomFieldBadRequest with default headers values
func NewUpdateTNCustomFieldBadRequest() *UpdateTNCustomFieldBadRequest {
	return &UpdateTNCustomFieldBadRequest{}
}

/* UpdateTNCustomFieldBadRequest describes a response with status code 400, with default header values.

Invalid data supplied
*/
type UpdateTNCustomFieldBadRequest struct {
	HttpResponse runtime.ClientResponse
}

// Code gets the status code for the update t n custom field bad request response
func (o *UpdateTNCustomFieldBadRequest) Code() int {
	return 400
}

// IsSuccess returns true when this update t n custom field bad request response has a 2xx status code
func (o *UpdateTNCustomFieldBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update t n custom field bad request response has a 3xx status code
func (o *UpdateTNCustomFieldBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update t n custom field bad request response has a 4xx status code
func (o *UpdateTNCustomFieldBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this update t n custom field bad request response has a 5xx status code
func (o *UpdateTNCustomFieldBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this update t n custom field bad request response a status code equal to that given
func (o *UpdateTNCustomFieldBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *UpdateTNCustomFieldBadRequest) Error() string {
	return fmt.Sprintf("[PUT /plugins/textnow-custom-field-plugin/][%d] updateTNCustomFieldBadRequest ", 400)
}

func (o *UpdateTNCustomFieldBadRequest) String() string {
	return fmt.Sprintf("[PUT /plugins/textnow-custom-field-plugin/][%d] updateTNCustomFieldBadRequest ", 400)
}

func (o *UpdateTNCustomFieldBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateTNCustomFieldInternalServerError creates a UpdateTNCustomFieldInternalServerError with default headers values
func NewUpdateTNCustomFieldInternalServerError() *UpdateTNCustomFieldInternalServerError {
	return &UpdateTNCustomFieldInternalServerError{}
}

/* UpdateTNCustomFieldInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type UpdateTNCustomFieldInternalServerError struct {
	HttpResponse runtime.ClientResponse
}

// Code gets the status code for the update t n custom field internal server error response
func (o *UpdateTNCustomFieldInternalServerError) Code() int {
	return 500
}

// IsSuccess returns true when this update t n custom field internal server error response has a 2xx status code
func (o *UpdateTNCustomFieldInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update t n custom field internal server error response has a 3xx status code
func (o *UpdateTNCustomFieldInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update t n custom field internal server error response has a 4xx status code
func (o *UpdateTNCustomFieldInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this update t n custom field internal server error response has a 5xx status code
func (o *UpdateTNCustomFieldInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this update t n custom field internal server error response a status code equal to that given
func (o *UpdateTNCustomFieldInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *UpdateTNCustomFieldInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /plugins/textnow-custom-field-plugin/][%d] updateTNCustomFieldInternalServerError ", 500)
}

func (o *UpdateTNCustomFieldInternalServerError) String() string {
	return fmt.Sprintf("[PUT /plugins/textnow-custom-field-plugin/][%d] updateTNCustomFieldInternalServerError ", 500)
}

func (o *UpdateTNCustomFieldInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
