// Code generated by go-swagger; DO NOT EDIT.

package healthcheck

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/killbill/kbcli/v3/kbcommon"

	"github.com/killbill/kbcli/v3/kbmodel"
)

// HealthcheckReader is a Reader for the Healthcheck structure.
type HealthcheckReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *HealthcheckReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewHealthcheckOK()
		result.HttpResponse = response
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		errorResult := kbcommon.NewKillbillError(response.Code())
		if err := consumer.Consume(response.Body(), &errorResult); err != nil && err != io.EOF {
			return nil, err
		}
		return nil, errorResult
	}
}

// NewHealthcheckOK creates a HealthcheckOK with default headers values
func NewHealthcheckOK() *HealthcheckOK {
	return &HealthcheckOK{}
}

/* HealthcheckOK describes a response with status code 200, with default header values.

successful operation
*/
type HealthcheckOK struct {
	Payload      *kbmodel.Healthcheck
	HttpResponse runtime.ClientResponse
}

// Code gets the status code for the healthcheck o k response
func (o *HealthcheckOK) Code() int {
	return 200
}

// IsSuccess returns true when this healthcheck o k response has a 2xx status code
func (o *HealthcheckOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this healthcheck o k response has a 3xx status code
func (o *HealthcheckOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this healthcheck o k response has a 4xx status code
func (o *HealthcheckOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this healthcheck o k response has a 5xx status code
func (o *HealthcheckOK) IsServerError() bool {
	return false
}

// IsCode returns true when this healthcheck o k response a status code equal to that given
func (o *HealthcheckOK) IsCode(code int) bool {
	return code == 200
}

func (o *HealthcheckOK) Error() string {
	return fmt.Sprintf("[GET /1.0/healthcheck][%d] healthcheckOK  %+v", 200, o.Payload)
}

func (o *HealthcheckOK) String() string {
	return fmt.Sprintf("[GET /1.0/healthcheck][%d] healthcheckOK  %+v", 200, o.Payload)
}

func (o *HealthcheckOK) GetPayload() *kbmodel.Healthcheck {
	return o.Payload
}

func (o *HealthcheckOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(kbmodel.Healthcheck)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
