// Code generated by go-swagger; DO NOT EDIT.

package kbmodel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Healthcheck healthcheck
//
// swagger:model Healthcheck
type Healthcheck struct {

	// main pool connectivity check
	MainPoolConnectivityCheck *HealthcheckMainPoolConnectivityCheck `json:"main.pool.ConnectivityCheck,omitempty"`
}

// Validate validates this healthcheck
func (m *Healthcheck) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMainPoolConnectivityCheck(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Healthcheck) validateMainPoolConnectivityCheck(formats strfmt.Registry) error {
	if swag.IsZero(m.MainPoolConnectivityCheck) { // not required
		return nil
	}

	if m.MainPoolConnectivityCheck != nil {
		if err := m.MainPoolConnectivityCheck.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("main.pool.ConnectivityCheck")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("main.pool.ConnectivityCheck")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this healthcheck based on the context it is used
func (m *Healthcheck) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMainPoolConnectivityCheck(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Healthcheck) contextValidateMainPoolConnectivityCheck(ctx context.Context, formats strfmt.Registry) error {

	if m.MainPoolConnectivityCheck != nil {
		if err := m.MainPoolConnectivityCheck.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("main.pool.ConnectivityCheck")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("main.pool.ConnectivityCheck")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Healthcheck) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Healthcheck) UnmarshalBinary(b []byte) error {
	var res Healthcheck
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// HealthcheckMainPoolConnectivityCheck healthcheck main pool connectivity check
//
// swagger:model HealthcheckMainPoolConnectivityCheck
type HealthcheckMainPoolConnectivityCheck struct {

	// healthy
	Healthy bool `json:"healthy,omitempty"`
}

// Validate validates this healthcheck main pool connectivity check
func (m *HealthcheckMainPoolConnectivityCheck) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this healthcheck main pool connectivity check based on context it is used
func (m *HealthcheckMainPoolConnectivityCheck) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HealthcheckMainPoolConnectivityCheck) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HealthcheckMainPoolConnectivityCheck) UnmarshalBinary(b []byte) error {
	var res HealthcheckMainPoolConnectivityCheck
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
