// Code generated by go-swagger; DO NOT EDIT.

package kbmodel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TNCustomField t n custom field
//
// swagger:model TNCustomField
type TNCustomField struct {

	// category
	Category string `json:"category,omitempty"`

	// data type
	DataType string `json:"dataType,omitempty"`

	// field name
	FieldName string `json:"fieldName,omitempty"`

	// field value
	FieldValue string `json:"fieldValue,omitempty"`

	// kb tenant Id
	KbTenantID string `json:"kbTenantId,omitempty"`

	// object Id
	ObjectID string `json:"objectId,omitempty"`
}

// Validate validates this t n custom field
func (m *TNCustomField) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this t n custom field based on context it is used
func (m *TNCustomField) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TNCustomField) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TNCustomField) UnmarshalBinary(b []byte) error {
	var res TNCustomField
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
